[package]
name = "ThalaSwapV2Interface"
version = "1.0.0"
authors = []

[addresses]
thalaswap_v2_interface = "0xABC"
thalaswap_v2_interface_deployer = "0xBEEF"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
