[package]
name = "ThalaSwapV1Demo"
version = "1.0.0"
authors = []

[addresses]
thalaswap_v1_demo = "0xABC"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.ThalaSwapV1Interface]
local = "../thalaswap_v1_interface/"
