[package]
name = "ThalaSwapV2Demo"
version = "1.0.0"
authors = []

[addresses]
thalaswap_v2_demo = "0xABC"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.ThalaSwapV2]
local = "../thalaswap_v2_interface/"
